config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'welcome/index'

   root 'welcome#index'

  resources :clicks
  resources :users, only: [:index, :show, :edit, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all                   # allow everyone to read everything

    if user && user.admin
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      can :manage, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true

  attr_accessor :created_at, :updated_at
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :clicks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    clicks_path
  end
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  layout "clicks"
  before_filter :authenticate_user!

  def initialize
    super # this calls ActionController::Base initialize
    @min = getMinMonth
  end

  def index
    @click = Click.new
    @month = Date.today.strftime("%m")
    @stat = getClickStat(@month)
    @max = @month
  end

  def email(from_addr)
    client = SendGrid::Client.new(api_user: ENV["SENDGRID_USERNAME"], api_key: ENV["SENDGRID_KEY"])

    mail = SendGrid::Mail.new do |m|
      m.to = 'careers@devbbq.com'
      m.from = from_addr
      m.subject = 'Email for Dev Assignment'
      m.text = 'Another person signed up to donate $1000 to Wikipedia.'
    end

    res = client.send(mail)
  end

  def getClickStat(month)
    result = Click.where('month(created_at) = ' + month).group("DATE_FORMAT(created_at, '%d')").count

    hash = {}
    result.each{|k,v|
      hash[k.to_i] = v
    } #mysql result doesn't contain dates with 0 click

    statistic = [] #force stat for each day
    (1..31).each{ |x|
      hash[x] ? statistic << hash[x] : statistic << 0
    }
    statistic
  end

  def getMinMonth
    Click.minimum('created_at').month
  end

  def show
    render json: getClickStat(params["id"])
  end

  def create
    params = {user_id: current_user.id}
    @click = Click.create(params)
    email current_user.email
    render json: current_user.id
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to clicks_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clicks/index.html.erb
<div class="mg-about">
  <div class="container">
    <div id="stat">
      <div>Click below to donate $1000 to Wikipedia monthly:</div>
      <br>

      <div id="result" class="alert alert-success" style="display: none;">Thank you for the donation!
      </div>

      <%= form_for(@click, remote: true) do |f| %>
          <%= f.submit 'Donate', class: "btn btn-theme" %>
      <% end %>
      <br><br>

      <div>Donors Sign Up Statistics by Month:</div>
      <div class="row">
        <div id="chart"></div>
      </div>

      <div class="demo demo2 text-center"></div>

      <p>Data available from <%= Date::MONTHNAMES[@min.to_i] %> to <%= Date::MONTHNAMES[@max.to_i] %>, <%= Time.now.year %></p>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function () {
    var month = <%= @month %>;
    var min = <%= @min %>;
    var max = <%= @max %>;

    plotGraph(<%= @stat %>, "Click Statistic for <%= Date::MONTHNAMES[@month.to_i] %>, 2015");

    $('.demo2').bootpag({
      total: max > min ? max - min + 1: max - min + 13,
      page: max > min ? max - min + 1: max - min + 13, //default page
      maxVisible: 3
    }).on('page', function (event, num) {
      month = num + min - 1 > 12 ? num + min - 13 : num + min - 1;
      getClickStat(month, min, max);
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DevBBQ</title>

  <link class="include" rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/clicks.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Donation Sign Up Bar Chart</title>

  <link class="include" rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link class="include" rel="stylesheet" type="text/css" href="https://s3-us-west-2.amazonaws.com/user-upload786/jglot/jquery.jqplot.min.css"/>
  <script type="text/javascript" src="https://s3-us-west-2.amazonaws.com/user-upload786/jglot/jquery.jqplot.min.js"></script>
  <script class="include" language="javascript" type="text/javascript" src="https://s3-us-west-2.amazonaws.com/user-upload786/jglot/plugins/jqplot.barRenderer.min.js"></script>
  <script class="include" language="javascript" type="text/javascript" src="https://s3-us-west-2.amazonaws.com/user-upload786/jglot/plugins/jqplot.pointLabels.min.js"></script>
  <script class="include" language="javascript" type="text/javascript" src="https://s3-us-west-2.amazonaws.com/user-upload786/jglot/plugins/jqplot.categoryAxisRenderer.min.js"></script>
</head>
<body>

<div id="devise" class="container text-right">
  <% if user_signed_in? %>
      <p>
        Logged in as <strong><%= current_user.email %></strong>.
      </p>

      <% if current_user.admin %>
          <%= link_to 'Rails Admin', rails_admin_path, :class => 'btn btn-theme' %>
      <% end %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-theme' %>
  <% else %>
      <%= link_to new_user_registration_path, :class => 'navbar-link btn btn-warning' do %>
          <span class="glyphicon glyphicon-heart"></span>Sign up
      <% end %>

      <%= link_to new_user_session_path, :class => 'navbar-link btn btn-success' do %>
          <span class="glyphicon glyphicon-share-alt"></span> Login
      <% end %>
  <% end %>
</div>
<br>

<%= yield %>

</body>
</html>

app/views/user_notifier/send_signup_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.name %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h1 style="visibility: hidden;">Welcome</h1>

      <h2 class="subtitle">Please sign in to use our app.</h2>

      <div id="countdown">Welcome</div>


      <%= link_to new_user_registration_path, :class => 'btn btn-theme' do %>
          Sign Up
      <% end %>

      <%= link_to new_user_session_path, :class => 'btn btn-theme' do %>
          <span class="glyphicon glyphicon-share-alt"></span> Login
      <% end %>

    </div>
  </div>
</div>